//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Giao_diện.Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        Giao_diện.Service.CompositeType GetDataUsingDataContract(Giao_diện.Service.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Giao_diện.Service.CompositeType> GetDataUsingDataContractAsync(Giao_diện.Service.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Dang_nhap", ReplyAction="http://tempuri.org/IService1/Dang_nhapResponse")]
        int Dang_nhap(string Ten_tai_khoan, string Mat_khau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Dang_nhap", ReplyAction="http://tempuri.org/IService1/Dang_nhapResponse")]
        System.Threading.Tasks.Task<int> Dang_nhapAsync(string Ten_tai_khoan, string Mat_khau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Doi_mat_khau", ReplyAction="http://tempuri.org/IService1/Doi_mat_khauResponse")]
        void Doi_mat_khau(string Ten_dang_nhap, string Mat_khau_moi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Doi_mat_khau", ReplyAction="http://tempuri.org/IService1/Doi_mat_khauResponse")]
        System.Threading.Tasks.Task Doi_mat_khauAsync(string Ten_dang_nhap, string Mat_khau_moi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Lay_khach_hang", ReplyAction="http://tempuri.org/IService1/Lay_khach_hangResponse")]
        DTO.Khach_hang Lay_khach_hang(string Ten_dang_nhap, string Mat_khau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Lay_khach_hang", ReplyAction="http://tempuri.org/IService1/Lay_khach_hangResponse")]
        System.Threading.Tasks.Task<DTO.Khach_hang> Lay_khach_hangAsync(string Ten_dang_nhap, string Mat_khau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Lay_so_tai_khoan", ReplyAction="http://tempuri.org/IService1/Lay_so_tai_khoanResponse")]
        string Lay_so_tai_khoan(string Ten_tai_khoan, string Mat_khau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Lay_so_tai_khoan", ReplyAction="http://tempuri.org/IService1/Lay_so_tai_khoanResponse")]
        System.Threading.Tasks.Task<string> Lay_so_tai_khoanAsync(string Ten_tai_khoan, string Mat_khau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Lay_so_tien", ReplyAction="http://tempuri.org/IService1/Lay_so_tienResponse")]
        double Lay_so_tien(string So_tai_khoan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Lay_so_tien", ReplyAction="http://tempuri.org/IService1/Lay_so_tienResponse")]
        System.Threading.Tasks.Task<double> Lay_so_tienAsync(string So_tai_khoan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Lay_tinh_trang", ReplyAction="http://tempuri.org/IService1/Lay_tinh_trangResponse")]
        int Lay_tinh_trang(string So_tai_khoan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Lay_tinh_trang", ReplyAction="http://tempuri.org/IService1/Lay_tinh_trangResponse")]
        System.Threading.Tasks.Task<int> Lay_tinh_trangAsync(string So_tai_khoan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Thay_doi_tinh_trang", ReplyAction="http://tempuri.org/IService1/Thay_doi_tinh_trangResponse")]
        void Thay_doi_tinh_trang(string So_tai_khoan, int Tinh_trang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Thay_doi_tinh_trang", ReplyAction="http://tempuri.org/IService1/Thay_doi_tinh_trangResponse")]
        System.Threading.Tasks.Task Thay_doi_tinh_trangAsync(string So_tai_khoan, int Tinh_trang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Them_chuyen_tien", ReplyAction="http://tempuri.org/IService1/Them_chuyen_tienResponse")]
        void Them_chuyen_tien(DTO.Chuyen_tien CT, string Loai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Them_chuyen_tien", ReplyAction="http://tempuri.org/IService1/Them_chuyen_tienResponse")]
        System.Threading.Tasks.Task Them_chuyen_tienAsync(DTO.Chuyen_tien CT, string Loai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Kiem_tra_tai_khoan", ReplyAction="http://tempuri.org/IService1/Kiem_tra_tai_khoanResponse")]
        bool Kiem_tra_tai_khoan(string So_tai_khoan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Kiem_tra_tai_khoan", ReplyAction="http://tempuri.org/IService1/Kiem_tra_tai_khoanResponse")]
        System.Threading.Tasks.Task<bool> Kiem_tra_tai_khoanAsync(string So_tai_khoan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Ds_chuyen_tien", ReplyAction="http://tempuri.org/IService1/Ds_chuyen_tienResponse")]
        DTO.Chuyen_tien[] Ds_chuyen_tien(string Stk_chuyen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Ds_chuyen_tien", ReplyAction="http://tempuri.org/IService1/Ds_chuyen_tienResponse")]
        System.Threading.Tasks.Task<DTO.Chuyen_tien[]> Ds_chuyen_tienAsync(string Stk_chuyen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Ds_nhan_tien", ReplyAction="http://tempuri.org/IService1/Ds_nhan_tienResponse")]
        DTO.Chuyen_tien[] Ds_nhan_tien(string Stk_nhan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Ds_nhan_tien", ReplyAction="http://tempuri.org/IService1/Ds_nhan_tienResponse")]
        System.Threading.Tasks.Task<DTO.Chuyen_tien[]> Ds_nhan_tienAsync(string Stk_nhan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Ds_chuyen_tien_tong", ReplyAction="http://tempuri.org/IService1/Ds_chuyen_tien_tongResponse")]
        DTO.Chuyen_tien[] Ds_chuyen_tien_tong(string So_tai_khoan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Ds_chuyen_tien_tong", ReplyAction="http://tempuri.org/IService1/Ds_chuyen_tien_tongResponse")]
        System.Threading.Tasks.Task<DTO.Chuyen_tien[]> Ds_chuyen_tien_tongAsync(string So_tai_khoan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Nap_tien", ReplyAction="http://tempuri.org/IService1/Nap_tienResponse")]
        void Nap_tien(string So_tai_khoan, double So_tien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Nap_tien", ReplyAction="http://tempuri.org/IService1/Nap_tienResponse")]
        System.Threading.Tasks.Task Nap_tienAsync(string So_tai_khoan, double So_tien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Tao_the_nap_tien", ReplyAction="http://tempuri.org/IService1/Tao_the_nap_tienResponse")]
        void Tao_the_nap_tien(double So_tien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Tao_the_nap_tien", ReplyAction="http://tempuri.org/IService1/Tao_the_nap_tienResponse")]
        System.Threading.Tasks.Task Tao_the_nap_tienAsync(double So_tien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Ds_nap_tien", ReplyAction="http://tempuri.org/IService1/Ds_nap_tienResponse")]
        DTO.Nap_tien[] Ds_nap_tien(string Stk_nap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Ds_nap_tien", ReplyAction="http://tempuri.org/IService1/Ds_nap_tienResponse")]
        System.Threading.Tasks.Task<DTO.Nap_tien[]> Ds_nap_tienAsync(string Stk_nap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Them_nap_tien", ReplyAction="http://tempuri.org/IService1/Them_nap_tienResponse")]
        int Them_nap_tien(DTO.Nap_tien temp, string Ma_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Them_nap_tien", ReplyAction="http://tempuri.org/IService1/Them_nap_tienResponse")]
        System.Threading.Tasks.Task<int> Them_nap_tienAsync(DTO.Nap_tien temp, string Ma_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Lay_so_tien_the", ReplyAction="http://tempuri.org/IService1/Lay_so_tien_theResponse")]
        double Lay_so_tien_the(string Ma_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Lay_so_tien_the", ReplyAction="http://tempuri.org/IService1/Lay_so_tien_theResponse")]
        System.Threading.Tasks.Task<double> Lay_so_tien_theAsync(string Ma_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Ds_the", ReplyAction="http://tempuri.org/IService1/Ds_theResponse")]
        DTO.The_nap_tien[] Ds_the();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Ds_the", ReplyAction="http://tempuri.org/IService1/Ds_theResponse")]
        System.Threading.Tasks.Task<DTO.The_nap_tien[]> Ds_theAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Tao_the_ngan_hang", ReplyAction="http://tempuri.org/IService1/Tao_the_ngan_hangResponse")]
        void Tao_the_ngan_hang(double So_tien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Tao_the_ngan_hang", ReplyAction="http://tempuri.org/IService1/Tao_the_ngan_hangResponse")]
        System.Threading.Tasks.Task Tao_the_ngan_hangAsync(double So_tien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Lay_loai_tai_khoan", ReplyAction="http://tempuri.org/IService1/Lay_loai_tai_khoanResponse")]
        string Lay_loai_tai_khoan(string So_tai_khoan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Lay_loai_tai_khoan", ReplyAction="http://tempuri.org/IService1/Lay_loai_tai_khoanResponse")]
        System.Threading.Tasks.Task<string> Lay_loai_tai_khoanAsync(string So_tai_khoan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Thay_doi_loai_tai_khoan", ReplyAction="http://tempuri.org/IService1/Thay_doi_loai_tai_khoanResponse")]
        void Thay_doi_loai_tai_khoan(string So_tai_khoan, string Loai_tai_khoan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Thay_doi_loai_tai_khoan", ReplyAction="http://tempuri.org/IService1/Thay_doi_loai_tai_khoanResponse")]
        System.Threading.Tasks.Task Thay_doi_loai_tai_khoanAsync(string So_tai_khoan, string Loai_tai_khoan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Rut_tien", ReplyAction="http://tempuri.org/IService1/Rut_tienResponse")]
        void Rut_tien(string So_tai_khoan, double So_tien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Rut_tien", ReplyAction="http://tempuri.org/IService1/Rut_tienResponse")]
        System.Threading.Tasks.Task Rut_tienAsync(string So_tai_khoan, double So_tien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Lay_ten_ngan_hang", ReplyAction="http://tempuri.org/IService1/Lay_ten_ngan_hangResponse")]
        string Lay_ten_ngan_hang();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Lay_ten_ngan_hang", ReplyAction="http://tempuri.org/IService1/Lay_ten_ngan_hangResponse")]
        System.Threading.Tasks.Task<string> Lay_ten_ngan_hangAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Doi_ten_ngan_hang", ReplyAction="http://tempuri.org/IService1/Doi_ten_ngan_hangResponse")]
        void Doi_ten_ngan_hang(string ten_moi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Doi_ten_ngan_hang", ReplyAction="http://tempuri.org/IService1/Doi_ten_ngan_hangResponse")]
        System.Threading.Tasks.Task Doi_ten_ngan_hangAsync(string ten_moi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Danh_sach_theo_ngay", ReplyAction="http://tempuri.org/IService1/Danh_sach_theo_ngayResponse")]
        DTO.Chuyen_tien[] Danh_sach_theo_ngay(System.DateTime bd, System.DateTime kt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Danh_sach_theo_ngay", ReplyAction="http://tempuri.org/IService1/Danh_sach_theo_ngayResponse")]
        System.Threading.Tasks.Task<DTO.Chuyen_tien[]> Danh_sach_theo_ngayAsync(System.DateTime bd, System.DateTime kt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Them_khach_hang", ReplyAction="http://tempuri.org/IService1/Them_khach_hangResponse")]
        void Them_khach_hang(DTO.Khach_hang khachhang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Them_khach_hang", ReplyAction="http://tempuri.org/IService1/Them_khach_hangResponse")]
        System.Threading.Tasks.Task Them_khach_hangAsync(DTO.Khach_hang khachhang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Thay_doi_khach_hang", ReplyAction="http://tempuri.org/IService1/Thay_doi_khach_hangResponse")]
        void Thay_doi_khach_hang(DTO.Khach_hang khachhang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Thay_doi_khach_hang", ReplyAction="http://tempuri.org/IService1/Thay_doi_khach_hangResponse")]
        System.Threading.Tasks.Task Thay_doi_khach_hangAsync(DTO.Khach_hang khachhang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Ds_khach", ReplyAction="http://tempuri.org/IService1/Ds_khachResponse")]
        DTO.Khach_hang[] Ds_khach();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Ds_khach", ReplyAction="http://tempuri.org/IService1/Ds_khachResponse")]
        System.Threading.Tasks.Task<DTO.Khach_hang[]> Ds_khachAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Them_tai_khoan", ReplyAction="http://tempuri.org/IService1/Them_tai_khoanResponse")]
        bool Them_tai_khoan(DTO.Tai_khoan Taikhoan, DTO.Dang_nhap dangnhap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Them_tai_khoan", ReplyAction="http://tempuri.org/IService1/Them_tai_khoanResponse")]
        System.Threading.Tasks.Task<bool> Them_tai_khoanAsync(DTO.Tai_khoan Taikhoan, DTO.Dang_nhap dangnhap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Ds_tai_khoan", ReplyAction="http://tempuri.org/IService1/Ds_tai_khoanResponse")]
        DTO.Tai_khoan[] Ds_tai_khoan();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Ds_tai_khoan", ReplyAction="http://tempuri.org/IService1/Ds_tai_khoanResponse")]
        System.Threading.Tasks.Task<DTO.Tai_khoan[]> Ds_tai_khoanAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Ma_khach_hang", ReplyAction="http://tempuri.org/IService1/Ma_khach_hangResponse")]
        string Ma_khach_hang();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Ma_khach_hang", ReplyAction="http://tempuri.org/IService1/Ma_khach_hangResponse")]
        System.Threading.Tasks.Task<string> Ma_khach_hangAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Ds_tai_khoan_theo_kh", ReplyAction="http://tempuri.org/IService1/Ds_tai_khoan_theo_khResponse")]
        DTO.Tai_khoan[] Ds_tai_khoan_theo_kh(string Ma_khach_hang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Ds_tai_khoan_theo_kh", ReplyAction="http://tempuri.org/IService1/Ds_tai_khoan_theo_khResponse")]
        System.Threading.Tasks.Task<DTO.Tai_khoan[]> Ds_tai_khoan_theo_khAsync(string Ma_khach_hang);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Giao_diện.Service.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Giao_diện.Service.IService1>, Giao_diện.Service.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public Giao_diện.Service.CompositeType GetDataUsingDataContract(Giao_diện.Service.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Giao_diện.Service.CompositeType> GetDataUsingDataContractAsync(Giao_diện.Service.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public int Dang_nhap(string Ten_tai_khoan, string Mat_khau) {
            return base.Channel.Dang_nhap(Ten_tai_khoan, Mat_khau);
        }
        
        public System.Threading.Tasks.Task<int> Dang_nhapAsync(string Ten_tai_khoan, string Mat_khau) {
            return base.Channel.Dang_nhapAsync(Ten_tai_khoan, Mat_khau);
        }
        
        public void Doi_mat_khau(string Ten_dang_nhap, string Mat_khau_moi) {
            base.Channel.Doi_mat_khau(Ten_dang_nhap, Mat_khau_moi);
        }
        
        public System.Threading.Tasks.Task Doi_mat_khauAsync(string Ten_dang_nhap, string Mat_khau_moi) {
            return base.Channel.Doi_mat_khauAsync(Ten_dang_nhap, Mat_khau_moi);
        }
        
        public DTO.Khach_hang Lay_khach_hang(string Ten_dang_nhap, string Mat_khau) {
            return base.Channel.Lay_khach_hang(Ten_dang_nhap, Mat_khau);
        }
        
        public System.Threading.Tasks.Task<DTO.Khach_hang> Lay_khach_hangAsync(string Ten_dang_nhap, string Mat_khau) {
            return base.Channel.Lay_khach_hangAsync(Ten_dang_nhap, Mat_khau);
        }
        
        public string Lay_so_tai_khoan(string Ten_tai_khoan, string Mat_khau) {
            return base.Channel.Lay_so_tai_khoan(Ten_tai_khoan, Mat_khau);
        }
        
        public System.Threading.Tasks.Task<string> Lay_so_tai_khoanAsync(string Ten_tai_khoan, string Mat_khau) {
            return base.Channel.Lay_so_tai_khoanAsync(Ten_tai_khoan, Mat_khau);
        }
        
        public double Lay_so_tien(string So_tai_khoan) {
            return base.Channel.Lay_so_tien(So_tai_khoan);
        }
        
        public System.Threading.Tasks.Task<double> Lay_so_tienAsync(string So_tai_khoan) {
            return base.Channel.Lay_so_tienAsync(So_tai_khoan);
        }
        
        public int Lay_tinh_trang(string So_tai_khoan) {
            return base.Channel.Lay_tinh_trang(So_tai_khoan);
        }
        
        public System.Threading.Tasks.Task<int> Lay_tinh_trangAsync(string So_tai_khoan) {
            return base.Channel.Lay_tinh_trangAsync(So_tai_khoan);
        }
        
        public void Thay_doi_tinh_trang(string So_tai_khoan, int Tinh_trang) {
            base.Channel.Thay_doi_tinh_trang(So_tai_khoan, Tinh_trang);
        }
        
        public System.Threading.Tasks.Task Thay_doi_tinh_trangAsync(string So_tai_khoan, int Tinh_trang) {
            return base.Channel.Thay_doi_tinh_trangAsync(So_tai_khoan, Tinh_trang);
        }
        
        public void Them_chuyen_tien(DTO.Chuyen_tien CT, string Loai) {
            base.Channel.Them_chuyen_tien(CT, Loai);
        }
        
        public System.Threading.Tasks.Task Them_chuyen_tienAsync(DTO.Chuyen_tien CT, string Loai) {
            return base.Channel.Them_chuyen_tienAsync(CT, Loai);
        }
        
        public bool Kiem_tra_tai_khoan(string So_tai_khoan) {
            return base.Channel.Kiem_tra_tai_khoan(So_tai_khoan);
        }
        
        public System.Threading.Tasks.Task<bool> Kiem_tra_tai_khoanAsync(string So_tai_khoan) {
            return base.Channel.Kiem_tra_tai_khoanAsync(So_tai_khoan);
        }
        
        public DTO.Chuyen_tien[] Ds_chuyen_tien(string Stk_chuyen) {
            return base.Channel.Ds_chuyen_tien(Stk_chuyen);
        }
        
        public System.Threading.Tasks.Task<DTO.Chuyen_tien[]> Ds_chuyen_tienAsync(string Stk_chuyen) {
            return base.Channel.Ds_chuyen_tienAsync(Stk_chuyen);
        }
        
        public DTO.Chuyen_tien[] Ds_nhan_tien(string Stk_nhan) {
            return base.Channel.Ds_nhan_tien(Stk_nhan);
        }
        
        public System.Threading.Tasks.Task<DTO.Chuyen_tien[]> Ds_nhan_tienAsync(string Stk_nhan) {
            return base.Channel.Ds_nhan_tienAsync(Stk_nhan);
        }
        
        public DTO.Chuyen_tien[] Ds_chuyen_tien_tong(string So_tai_khoan) {
            return base.Channel.Ds_chuyen_tien_tong(So_tai_khoan);
        }
        
        public System.Threading.Tasks.Task<DTO.Chuyen_tien[]> Ds_chuyen_tien_tongAsync(string So_tai_khoan) {
            return base.Channel.Ds_chuyen_tien_tongAsync(So_tai_khoan);
        }
        
        public void Nap_tien(string So_tai_khoan, double So_tien) {
            base.Channel.Nap_tien(So_tai_khoan, So_tien);
        }
        
        public System.Threading.Tasks.Task Nap_tienAsync(string So_tai_khoan, double So_tien) {
            return base.Channel.Nap_tienAsync(So_tai_khoan, So_tien);
        }
        
        public void Tao_the_nap_tien(double So_tien) {
            base.Channel.Tao_the_nap_tien(So_tien);
        }
        
        public System.Threading.Tasks.Task Tao_the_nap_tienAsync(double So_tien) {
            return base.Channel.Tao_the_nap_tienAsync(So_tien);
        }
        
        public DTO.Nap_tien[] Ds_nap_tien(string Stk_nap) {
            return base.Channel.Ds_nap_tien(Stk_nap);
        }
        
        public System.Threading.Tasks.Task<DTO.Nap_tien[]> Ds_nap_tienAsync(string Stk_nap) {
            return base.Channel.Ds_nap_tienAsync(Stk_nap);
        }
        
        public int Them_nap_tien(DTO.Nap_tien temp, string Ma_code) {
            return base.Channel.Them_nap_tien(temp, Ma_code);
        }
        
        public System.Threading.Tasks.Task<int> Them_nap_tienAsync(DTO.Nap_tien temp, string Ma_code) {
            return base.Channel.Them_nap_tienAsync(temp, Ma_code);
        }
        
        public double Lay_so_tien_the(string Ma_code) {
            return base.Channel.Lay_so_tien_the(Ma_code);
        }
        
        public System.Threading.Tasks.Task<double> Lay_so_tien_theAsync(string Ma_code) {
            return base.Channel.Lay_so_tien_theAsync(Ma_code);
        }
        
        public DTO.The_nap_tien[] Ds_the() {
            return base.Channel.Ds_the();
        }
        
        public System.Threading.Tasks.Task<DTO.The_nap_tien[]> Ds_theAsync() {
            return base.Channel.Ds_theAsync();
        }
        
        public void Tao_the_ngan_hang(double So_tien) {
            base.Channel.Tao_the_ngan_hang(So_tien);
        }
        
        public System.Threading.Tasks.Task Tao_the_ngan_hangAsync(double So_tien) {
            return base.Channel.Tao_the_ngan_hangAsync(So_tien);
        }
        
        public string Lay_loai_tai_khoan(string So_tai_khoan) {
            return base.Channel.Lay_loai_tai_khoan(So_tai_khoan);
        }
        
        public System.Threading.Tasks.Task<string> Lay_loai_tai_khoanAsync(string So_tai_khoan) {
            return base.Channel.Lay_loai_tai_khoanAsync(So_tai_khoan);
        }
        
        public void Thay_doi_loai_tai_khoan(string So_tai_khoan, string Loai_tai_khoan) {
            base.Channel.Thay_doi_loai_tai_khoan(So_tai_khoan, Loai_tai_khoan);
        }
        
        public System.Threading.Tasks.Task Thay_doi_loai_tai_khoanAsync(string So_tai_khoan, string Loai_tai_khoan) {
            return base.Channel.Thay_doi_loai_tai_khoanAsync(So_tai_khoan, Loai_tai_khoan);
        }
        
        public void Rut_tien(string So_tai_khoan, double So_tien) {
            base.Channel.Rut_tien(So_tai_khoan, So_tien);
        }
        
        public System.Threading.Tasks.Task Rut_tienAsync(string So_tai_khoan, double So_tien) {
            return base.Channel.Rut_tienAsync(So_tai_khoan, So_tien);
        }
        
        public string Lay_ten_ngan_hang() {
            return base.Channel.Lay_ten_ngan_hang();
        }
        
        public System.Threading.Tasks.Task<string> Lay_ten_ngan_hangAsync() {
            return base.Channel.Lay_ten_ngan_hangAsync();
        }
        
        public void Doi_ten_ngan_hang(string ten_moi) {
            base.Channel.Doi_ten_ngan_hang(ten_moi);
        }
        
        public System.Threading.Tasks.Task Doi_ten_ngan_hangAsync(string ten_moi) {
            return base.Channel.Doi_ten_ngan_hangAsync(ten_moi);
        }
        
        public DTO.Chuyen_tien[] Danh_sach_theo_ngay(System.DateTime bd, System.DateTime kt) {
            return base.Channel.Danh_sach_theo_ngay(bd, kt);
        }
        
        public System.Threading.Tasks.Task<DTO.Chuyen_tien[]> Danh_sach_theo_ngayAsync(System.DateTime bd, System.DateTime kt) {
            return base.Channel.Danh_sach_theo_ngayAsync(bd, kt);
        }
        
        public void Them_khach_hang(DTO.Khach_hang khachhang) {
            base.Channel.Them_khach_hang(khachhang);
        }
        
        public System.Threading.Tasks.Task Them_khach_hangAsync(DTO.Khach_hang khachhang) {
            return base.Channel.Them_khach_hangAsync(khachhang);
        }
        
        public void Thay_doi_khach_hang(DTO.Khach_hang khachhang) {
            base.Channel.Thay_doi_khach_hang(khachhang);
        }
        
        public System.Threading.Tasks.Task Thay_doi_khach_hangAsync(DTO.Khach_hang khachhang) {
            return base.Channel.Thay_doi_khach_hangAsync(khachhang);
        }
        
        public DTO.Khach_hang[] Ds_khach() {
            return base.Channel.Ds_khach();
        }
        
        public System.Threading.Tasks.Task<DTO.Khach_hang[]> Ds_khachAsync() {
            return base.Channel.Ds_khachAsync();
        }
        
        public bool Them_tai_khoan(DTO.Tai_khoan Taikhoan, DTO.Dang_nhap dangnhap) {
            return base.Channel.Them_tai_khoan(Taikhoan, dangnhap);
        }
        
        public System.Threading.Tasks.Task<bool> Them_tai_khoanAsync(DTO.Tai_khoan Taikhoan, DTO.Dang_nhap dangnhap) {
            return base.Channel.Them_tai_khoanAsync(Taikhoan, dangnhap);
        }
        
        public DTO.Tai_khoan[] Ds_tai_khoan() {
            return base.Channel.Ds_tai_khoan();
        }
        
        public System.Threading.Tasks.Task<DTO.Tai_khoan[]> Ds_tai_khoanAsync() {
            return base.Channel.Ds_tai_khoanAsync();
        }
        
        public string Ma_khach_hang() {
            return base.Channel.Ma_khach_hang();
        }
        
        public System.Threading.Tasks.Task<string> Ma_khach_hangAsync() {
            return base.Channel.Ma_khach_hangAsync();
        }
        
        public DTO.Tai_khoan[] Ds_tai_khoan_theo_kh(string Ma_khach_hang) {
            return base.Channel.Ds_tai_khoan_theo_kh(Ma_khach_hang);
        }
        
        public System.Threading.Tasks.Task<DTO.Tai_khoan[]> Ds_tai_khoan_theo_khAsync(string Ma_khach_hang) {
            return base.Channel.Ds_tai_khoan_theo_khAsync(Ma_khach_hang);
        }
    }
}
